# Generated by Django 6.0.3 on 2026-03-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True, help_text='Zaman serisi analizi için işlem tarihi'),
        ),
    ]
